# Generated by Django 5.1.4 on 2025-01-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.PositiveSmallIntegerField()),
                ("gender", models.CharField(max_length=10)),
                ("color", models.CharField(max_length=50)),
                ("favorite_food", models.CharField(max_length=100)),
                ("favorite_toy", models.CharField(max_length=100)),
            ],
        ),
    ]
