# Generated by Django 5.1.4 on 2025-01-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dogs", "0002_breed_alter_dog_gender_dog_breed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="breed",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
