services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./Django_project:/Django_project
    env_file:
      - .env-non-dev
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db


  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=dogs_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
